export const GET_USER_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_INFO_FAILURE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
